### ISSUE TITLE
Formularfunktionen gehen mit LO 7.1.2.2 und Wollmux 18.2.2 nicht

### ISSUE THREAD

**Issue by hkrahe** [LibreOffice/lots#346]
Hallo zusammen,

vorab: das Verlagern der Wollmuxbar in die Seitenleiste finde ich eine gute Idee, grundsätzlich läuft das auch. Bei uns läuft aktuell LO 7.1.2.2 auf einem Suse-Server Enterprise 15 SP2, hier teste ich verschiedene Wollmux-Versionen ab Version 18.1.8.
Zum einen habe ich festgestellt, dass der Wollmux bei uns was Java angeht nur mit der Oracle 11.x-Version funktioniert. 
Das über Pop-Up-Fenster (mit Formularmax 4000 angelegt) angesteuerte Ein-/Ausblenden von Texten z.B. über Check-Boxen funktioniert gar nicht, es gibt keine Reaktion im Dokument. Letzendlich werden da ja nur definierte Bereiche eingeblendet ode rauch nicht.
Auch sind die in der Seitenleiste untergebrachten Tabs zur Dateneingabe bei Formularen meist zu klein, kann man irgendwo eine Mindestgröße einstellen ? Früher hat man im Formularmax einfach im Tab ein paar Zeilen mehr als eigentlich notwendig angelegt und später im Dokument war das Eingabefenster immer groß genug für alle Dateneingaben.

Beim Serienbrief ist mir aufgefallen, dass Geldsummen aus einer Datenquelle nicht als formatierte Währungsfelder in den Serienbrief übernommen werden, sodass z.B. aus 9,90 € plötzlich 9,9 werden, das kriege ich auch nicht geändert, egal wie ich die Zellen im Calc definiere, im Serienbrief ist die Formatierung weg.

Vielen Dank im Voraus für sachdienliche Hinweise.

Gruß

Holger Krahé

**Comment by smehrbrodt** [comment]
> Das über Pop-Up-Fenster (mit Formularmax 4000 angelegt) angesteuerte Ein-/Ausblenden von Texten z.B. über Check-Boxen funktioniert gar nicht, es gibt keine Reaktion im Dokument. Letzendlich werden da ja nur definierte Bereiche eingeblendet ode rauch nicht.

Wie genau kann ich das nachstellen?

> Auch sind die in der Seitenleiste untergebrachten Tabs zur Dateneingabe bei Formularen meist zu klein, kann man irgendwo eine Mindestgröße einstellen ? Früher hat man im Formularmax einfach im Tab ein paar Zeilen mehr als eigentlich notwendig angelegt und später im Dokument war das Eingabefenster immer groß genug für alle Dateneingaben.

Bitte ein separates Ticket dafür anlegen.

> Beim Serienbrief ist mir aufgefallen, dass Geldsummen aus einer Datenquelle nicht als formatierte Währungsfelder in den Serienbrief übernommen werden, sodass z.B. aus 9,90 € plötzlich 9,9 werden, das kriege ich auch nicht geändert, egal wie ich die Zellen im Calc definiere, im Serienbrief ist die Formatierung weg.

Bitte ebenfalls ein separates Ticket anlegen, mit Beispieldatei und den genauen Schritten, wie der Fehler nachgestellt werden kann.
