### ISSUE TITLE
Accept English section names in config files

### ISSUE THREAD

**Issue by kelemeng** [LibreOffice/lots#432]
Currently most section names in the config files are in German.
For wider adoption it would be better to be able to provide these in English.
See the files in https://github.com/LibreOffice/wollmux-config/tree/main/.wollmux/config/conf
Some examples:
oooEinstellungen.conf: OOoEinstellungen
funktionen.conf: Funktionen, Druckfunktionen
email.conf: EMailEinstellungen
datenquellen.conf: Datenquellen, Datenquelle, PersoenlicheAbsenderlisteInitialisierung, Suchstrategie
textbausteine.conf: Textbausteine, Warnungen, Kuerzel, Textfragmente
tastenkuerzel.conf: Tastenkuerzel (also it uses the strg as key - maybe support Ctrl here?)
formularmax4000.conf: Standardelemente, Empfaengerauswahl, Eingabefelder, 
referat.conf: AbsenderdatenSpaltenumsetzung, ExterneAnwendungen, SachleitendeVerfuegungen, Funktionsdialoge
adressauswahl-referat.conf, adressauswahl-standard.conf: Suche, Spaltenumsetzung, Suchergebnis, Vorschau, Fussbereich
Dateinamensanpassung.conf: VerfuegbarenPfadVerwenden
wollmuxbar_standard.conf: Menueleiste, Symbolleisten, Briefkopfleiste, Menues, Elemente
mapDienstBezKurzLang.conf, mapDienstgebaeude.conf, mapOrgaKurz.conf, mapReferent.conf: Daten

**Comment by smehrbrodt** [comment]
Having this app support both German and English would need major changes in the source code, so I just changed them to English. Will document the required changes in the config in case anyone upgrades from WollMux to LOTS.
