### ISSUE TITLE
I hope Math can support handwritten formula components.

### ISSUE THREAD

**Issue by ToKingl** [LibreOffice/lots#467]
As the title says, I hope Math can support handwritten formulas, so that you can write formulas directly with a touch pen or mouse, which is much more convenient than the current scheme.

**Comment by ToKingl** [comment]
Something like this,
![Uploading Image_1700871880654.jpg…]()

**Comment by smehrbrodt** [comment]
This is not the LibreOffice bugtracker, please use https://ask.libreoffice.org/
